package com.jvitor.portfolioapi.controller.projects;

import com.fasterxml.jackson.annotation.JsonProperty;

public enum TagsProject {
    JAVA,
    SPRING,
    SPRING_BOOT,
    DOCKER,
    KUBERNETES,
    @JsonProperty("DJANGO")
    DJANGO,
    @JsonProperty("PYTHON")
    PYTHON,
    JAVASCRIPT,
    TYPESCRIPT,
    REACT,
    ANGULAR,
    VUE,
    HTML,
    CSS,
    SASS,
    SCSS,
    BOOTSTRAP,
    MATERIAL_UI,
    TAILWIND_CSS,
    JQUERY,
    MYSQL,
    POSTGRESQL,
    MONGODB,
    SQL_SERVER,
    ORACLE,
    FIREBASE,
    GIT,
    GITHUB,
    GITLAB,
    BITBUCKET,
    JENKINS,
    TRAVIS_CI,
    CIRCLE_CI,
    HEROKU,
    AWS,
    AZURE,
    GOOGLE_CLOUD,
}
